// This file is generated by omniidl (C++ backend) - omniORB_4_3. Do not edit.

#include "classes.hh"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

OMNI_MAYBE_UNUSED static const char* _0RL_library_version = omniORB_4_3;



::CORBA::Exception::insertExceptionToAny Classes::ErreurClasse::insertToAnyFn = 0;
::CORBA::Exception::insertExceptionToAnyNCP Classes::ErreurClasse::insertToAnyFnNCP = 0;

Classes::ErreurClasse::ErreurClasse(const Classes::ErreurClasse& _s) : ::CORBA::UserException(_s)
{
  message = _s.message;

}

Classes::ErreurClasse::ErreurClasse(const char* _message)
{
  pd_insertToAnyFn    = Classes::ErreurClasse::insertToAnyFn;
  pd_insertToAnyFnNCP = Classes::ErreurClasse::insertToAnyFnNCP;
  message = _message;

}



Classes::ErreurClasse& Classes::ErreurClasse::operator=(const Classes::ErreurClasse& _s)
{
  if (&_s != this) {
    ((::CORBA::UserException*) this)->operator=(_s);
    message = _s.message;

  }
  return *this;
}

Classes::ErreurClasse::~ErreurClasse() {}

void Classes::ErreurClasse::_raise() const { throw *this; }

const char* Classes::ErreurClasse::_PD_repoId = "IDL:Classes/ErreurClasse:1.0";
const char* Classes::ErreurClasse::_PD_typeId = "Exception/UserException/Classes::ErreurClasse";

Classes::ErreurClasse* Classes::ErreurClasse::_downcast(::CORBA::Exception* _e) {
  return (ErreurClasse*) _NP_is_a(_e, _PD_typeId);
}

const Classes::ErreurClasse* Classes::ErreurClasse::_downcast(const ::CORBA::Exception* _e) {
  return (const ErreurClasse*) _NP_is_a(_e, _PD_typeId);
}

::CORBA::Exception* Classes::ErreurClasse::_NP_duplicate() const {
  return new ErreurClasse(*this);
}

const char* Classes::ErreurClasse::_NP_typeId() const {
  return _PD_typeId;
}

const char* Classes::ErreurClasse::_NP_repoId(int* _size) const {
  *_size = sizeof("IDL:Classes/ErreurClasse:1.0");
  return _PD_repoId;
}
 
void Classes::ErreurClasse::_NP_marshal(cdrStream& _s) const {
  *this >>= _s;
}

void
Classes::ErreurClasse::operator>>= (cdrStream& _n) const
{
  _n.marshalString(message,0);

}

void
Classes::ErreurClasse::operator<<= (cdrStream& _n)
{
  message = _n.unmarshalString(0);

}

Classes::GestionClasses_ptr Classes::GestionClasses_Helper::_nil() {
  return ::Classes::GestionClasses::_nil();
}

::CORBA::Boolean Classes::GestionClasses_Helper::is_nil(::Classes::GestionClasses_ptr p) {
  return ::CORBA::is_nil(p);

}

void Classes::GestionClasses_Helper::release(::Classes::GestionClasses_ptr p) {
  ::CORBA::release(p);
}

void Classes::GestionClasses_Helper::marshalObjRef(::Classes::GestionClasses_ptr obj, cdrStream& s) {
  ::Classes::GestionClasses::_marshalObjRef(obj, s);
}

Classes::GestionClasses_ptr Classes::GestionClasses_Helper::unmarshalObjRef(cdrStream& s) {
  return ::Classes::GestionClasses::_unmarshalObjRef(s);
}

void Classes::GestionClasses_Helper::duplicate(::Classes::GestionClasses_ptr obj) {
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
}

Classes::GestionClasses_ptr
Classes::GestionClasses::_duplicate(::Classes::GestionClasses_ptr obj)
{
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
  return obj;
}

Classes::GestionClasses_ptr
Classes::GestionClasses::_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


Classes::GestionClasses_ptr
Classes::GestionClasses::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

Classes::GestionClasses_ptr
Classes::GestionClasses::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_GestionClasses _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_GestionClasses* _the_nil_ptr = 0;
  if (!_the_nil_ptr) {
    omni::nilRefLock().lock();
    if (!_the_nil_ptr) {
      _the_nil_ptr = new _objref_GestionClasses;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* Classes::GestionClasses::_PD_repoId = "IDL:Classes/GestionClasses:1.0";


Classes::_objref_GestionClasses::~_objref_GestionClasses() {
  
}


Classes::_objref_GestionClasses::_objref_GestionClasses(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::Classes::GestionClasses::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
Classes::_objref_GestionClasses::_ptrToObjRef(const char* id)
{
  if (id == ::Classes::GestionClasses::_PD_repoId)
    return (::Classes::GestionClasses_ptr) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (::CORBA::Object_ptr) this;

  if (omni::strMatch(id, ::Classes::GestionClasses::_PD_repoId))
    return (::Classes::GestionClasses_ptr) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (::CORBA::Object_ptr) this;

  return 0;
}


//
// Code for Classes::GestionClasses::listerClasses

// Proxy call descriptor class. Mangled signature:
//  _cClasses_mListeNoms_e_cClasses_mErreurClasse
class _0RL_cd_32876cce75c60dd2_00000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_32876cce75c60dd2_00000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 1, upcall)
  {
    
  }
  
  
  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  void userException(cdrStream&, _OMNI_NS(IOP_C)*, const char*);
  static const char* const _user_exns[];

  Classes::ListeNoms_var result;
};

void _0RL_cd_32876cce75c60dd2_00000000::marshalReturnedValues(cdrStream& _n)
{
  (const Classes::ListeNoms&) result >>= _n;

}

void _0RL_cd_32876cce75c60dd2_00000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = new Classes::ListeNoms;
  (Classes::ListeNoms&)result <<= _n;

}

const char* const _0RL_cd_32876cce75c60dd2_00000000::_user_exns[] = {
  Classes::ErreurClasse::_PD_repoId
};

void _0RL_cd_32876cce75c60dd2_00000000::userException(cdrStream& s, _OMNI_NS(IOP_C)* iop_client, const char* repoId)
{
  if (omni::strMatch(repoId, Classes::ErreurClasse::_PD_repoId)) {
    Classes::ErreurClasse _ex;
    _ex <<= s;
    if (iop_client) iop_client->RequestCompleted();
    throw _ex;
  }


  else {
    if (iop_client) iop_client->RequestCompleted(1);
    OMNIORB_THROW(UNKNOWN,UNKNOWN_UserException,
                  (::CORBA::CompletionStatus)s.completion());
  }
}

// Local call call-back function.
static void
_0RL_lcfn_32876cce75c60dd2_10000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_32876cce75c60dd2_00000000* tcd = (_0RL_cd_32876cce75c60dd2_00000000*)cd;
  Classes::_impl_GestionClasses* impl = (Classes::_impl_GestionClasses*) svnt->_ptrToInterface(Classes::GestionClasses::_PD_repoId);
#ifdef OMNI_HAS_Cplusplus_catch_exception_by_base
  tcd->result = impl->listerClasses();
#else
  if (!cd->is_upcall())
    tcd->result = impl->listerClasses();
  else {
    try {
      tcd->result = impl->listerClasses();
    }
    catch(Classes::ErreurClasse& ex) {
      throw omniORB::StubUserException(ex._NP_duplicate());
    }


  }
#endif


}

Classes::ListeNoms* Classes::_objref_GestionClasses::listerClasses()
{
  _0RL_cd_32876cce75c60dd2_00000000 _call_desc(_0RL_lcfn_32876cce75c60dd2_10000000, "listerClasses", 14);


  _invoke(_call_desc);
  return _call_desc.result._retn();


}


//
// Code for Classes::GestionClasses::listerEtudiants

// Proxy call descriptor class. Mangled signature:
//  _cClasses_mListeNoms_i_cstring_e_cClasses_mErreurClasse
class _0RL_cd_32876cce75c60dd2_20000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_32876cce75c60dd2_20000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 1, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  void userException(cdrStream&, _OMNI_NS(IOP_C)*, const char*);
  static const char* const _user_exns[];

  ::CORBA::String_var arg_0_;
  const char* arg_0;
  Classes::ListeNoms_var result;
};

void _0RL_cd_32876cce75c60dd2_20000000::marshalArguments(cdrStream& _n)
{
  _n.marshalString(arg_0,0);

}

void _0RL_cd_32876cce75c60dd2_20000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = _n.unmarshalString(0);
  arg_0 = arg_0_.in();

}

void _0RL_cd_32876cce75c60dd2_20000000::marshalReturnedValues(cdrStream& _n)
{
  (const Classes::ListeNoms&) result >>= _n;

}

void _0RL_cd_32876cce75c60dd2_20000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = new Classes::ListeNoms;
  (Classes::ListeNoms&)result <<= _n;

}

const char* const _0RL_cd_32876cce75c60dd2_20000000::_user_exns[] = {
  Classes::ErreurClasse::_PD_repoId
};

void _0RL_cd_32876cce75c60dd2_20000000::userException(cdrStream& s, _OMNI_NS(IOP_C)* iop_client, const char* repoId)
{
  if (omni::strMatch(repoId, Classes::ErreurClasse::_PD_repoId)) {
    Classes::ErreurClasse _ex;
    _ex <<= s;
    if (iop_client) iop_client->RequestCompleted();
    throw _ex;
  }


  else {
    if (iop_client) iop_client->RequestCompleted(1);
    OMNIORB_THROW(UNKNOWN,UNKNOWN_UserException,
                  (::CORBA::CompletionStatus)s.completion());
  }
}

// Local call call-back function.
static void
_0RL_lcfn_32876cce75c60dd2_30000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_32876cce75c60dd2_20000000* tcd = (_0RL_cd_32876cce75c60dd2_20000000*)cd;
  Classes::_impl_GestionClasses* impl = (Classes::_impl_GestionClasses*) svnt->_ptrToInterface(Classes::GestionClasses::_PD_repoId);
#ifdef OMNI_HAS_Cplusplus_catch_exception_by_base
  tcd->result = impl->listerEtudiants(tcd->arg_0);
#else
  if (!cd->is_upcall())
    tcd->result = impl->listerEtudiants(tcd->arg_0);
  else {
    try {
      tcd->result = impl->listerEtudiants(tcd->arg_0);
    }
    catch(Classes::ErreurClasse& ex) {
      throw omniORB::StubUserException(ex._NP_duplicate());
    }


  }
#endif


}

Classes::ListeNoms* Classes::_objref_GestionClasses::listerEtudiants(const char* nomClasse)
{
  _0RL_cd_32876cce75c60dd2_20000000 _call_desc(_0RL_lcfn_32876cce75c60dd2_30000000, "listerEtudiants", 16);
  _call_desc.arg_0 = nomClasse;

  _invoke(_call_desc);
  return _call_desc.result._retn();


}

Classes::_pof_GestionClasses::~_pof_GestionClasses() {}


omniObjRef*
Classes::_pof_GestionClasses::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::Classes::_objref_GestionClasses(ior, id);
}


::CORBA::Boolean
Classes::_pof_GestionClasses::is_a(const char* id) const
{
  if (omni::ptrStrMatch(id, ::Classes::GestionClasses::_PD_repoId))
    return 1;
  
  return 0;
}

const Classes::_pof_GestionClasses _the_pof_Classes_mGestionClasses;

Classes::_impl_GestionClasses::~_impl_GestionClasses() {}


::CORBA::Boolean
Classes::_impl_GestionClasses::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if (omni::strMatch(op, "listerClasses")) {

    _0RL_cd_32876cce75c60dd2_00000000 _call_desc(_0RL_lcfn_32876cce75c60dd2_10000000, "listerClasses", 14, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "listerEtudiants")) {

    _0RL_cd_32876cce75c60dd2_20000000 _call_desc(_0RL_lcfn_32876cce75c60dd2_30000000, "listerEtudiants", 16, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
Classes::_impl_GestionClasses::_ptrToInterface(const char* id)
{
  if (id == ::Classes::GestionClasses::_PD_repoId)
    return (::Classes::_impl_GestionClasses*) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (void*) 1;

  if (omni::strMatch(id, ::Classes::GestionClasses::_PD_repoId))
    return (::Classes::_impl_GestionClasses*) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (void*) 1;
  return 0;
}

const char*
Classes::_impl_GestionClasses::_mostDerivedRepoId()
{
  return ::Classes::GestionClasses::_PD_repoId;
}

POA_Classes::GestionClasses::~GestionClasses() {}

