// This file is generated by omniidl (C++ backend)- omniORB_4_3. Do not edit.
#ifndef __classes_hh__
#define __classes_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_classes
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_classes
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_classes
#endif






#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif



_CORBA_MODULE Classes

_CORBA_MODULE_BEG

  class ListeNoms_var;

  class ListeNoms : public _CORBA_Unbounded_Sequence_String {
  public:
    typedef ListeNoms_var _var_type;
    inline ListeNoms() {}
    inline ListeNoms(const ListeNoms& _s)
      : _CORBA_Unbounded_Sequence_String(_s) {}

    inline ListeNoms(_CORBA_ULong _max)
      : _CORBA_Unbounded_Sequence_String(_max) {}
    inline ListeNoms(_CORBA_ULong _max, _CORBA_ULong _len, char** _val, _CORBA_Boolean _rel=0)
      : _CORBA_Unbounded_Sequence_String(_max, _len, _val, _rel) {}

  

    inline ListeNoms& operator = (const ListeNoms& _s) {
      _CORBA_Unbounded_Sequence_String::operator=(_s);
      return *this;
    }
  };

  class ListeNoms_out;

  class ListeNoms_var {
  public:
    inline ListeNoms_var() : _pd_seq(0) {}
    inline ListeNoms_var(ListeNoms* _s) : _pd_seq(_s) {}
    inline ListeNoms_var(const ListeNoms_var& _s) {
      if (_s._pd_seq)  _pd_seq = new ListeNoms(*_s._pd_seq);
      else             _pd_seq = 0;
    }
    inline ~ListeNoms_var() { if (_pd_seq)  delete _pd_seq; }
      
    inline ListeNoms_var& operator = (ListeNoms* _s) {
      if (_pd_seq)  delete _pd_seq;
      _pd_seq = _s;
      return *this;
    }
    inline ListeNoms_var& operator = (const ListeNoms_var& _s) {
      if (&_s != this) {
        if (_s._pd_seq) {
          if (!_pd_seq)  _pd_seq = new ListeNoms;
          *_pd_seq = *_s._pd_seq;
        }
        else if (_pd_seq) {
          delete _pd_seq;
          _pd_seq = 0;
        }
      }
      return *this;
    }
    inline _CORBA_String_element operator [] (_CORBA_ULong _s) {
      return (*_pd_seq)[_s];
    }

  

    inline ListeNoms* operator -> () { return _pd_seq; }
    inline const ListeNoms* operator -> () const { return _pd_seq; }
#if defined(__GNUG__)
    inline operator ListeNoms& () const { return *_pd_seq; }
#else
    inline operator const ListeNoms& () const { return *_pd_seq; }
    inline operator ListeNoms& () { return *_pd_seq; }
#endif
      
    inline const ListeNoms& in() const { return *_pd_seq; }
    inline ListeNoms&       inout()    { return *_pd_seq; }
    inline ListeNoms*&      out() {
      if (_pd_seq) { delete _pd_seq; _pd_seq = 0; }
      return _pd_seq;
    }
    inline ListeNoms* _retn() { ListeNoms* tmp = _pd_seq; _pd_seq = 0; return tmp; }
      
    friend class ListeNoms_out;
    
  private:
    ListeNoms* _pd_seq;
  };

  class ListeNoms_out {
  public:
    inline ListeNoms_out(ListeNoms*& _s) : _data(_s) { _data = 0; }
    inline ListeNoms_out(ListeNoms_var& _s)
      : _data(_s._pd_seq) { _s = (ListeNoms*) 0; }
    inline ListeNoms_out(const ListeNoms_out& _s) : _data(_s._data) {}
    inline ListeNoms_out& operator = (const ListeNoms_out& _s) {
      _data = _s._data;
      return *this;
    }
    inline ListeNoms_out& operator = (ListeNoms* _s) {
      _data = _s;
      return *this;
    }
    inline operator ListeNoms*&()  { return _data; }
    inline ListeNoms*& ptr()       { return _data; }
    inline ListeNoms* operator->() { return _data; }

    inline _CORBA_String_element operator [] (_CORBA_ULong _i) {
      return (*_data)[_i];
    }

  

    ListeNoms*& _data;

  private:
    ListeNoms_out();
    ListeNoms_out& operator=(const ListeNoms_var&);
  };

  class ErreurClasse : public ::CORBA::UserException {
  public:
    
    ::CORBA::String_member message;

  

    inline ErreurClasse() {
      pd_insertToAnyFn    = insertToAnyFn;
      pd_insertToAnyFnNCP = insertToAnyFnNCP;
    }
    ErreurClasse(const ErreurClasse&);
    ErreurClasse(const char* i_message);
    ErreurClasse& operator=(const ErreurClasse&);
    virtual ~ErreurClasse();
    virtual void _raise() const;
    static ErreurClasse* _downcast(::CORBA::Exception*);
    static const ErreurClasse* _downcast(const ::CORBA::Exception*);
    static inline ErreurClasse* _narrow(::CORBA::Exception* _e) {
      return _downcast(_e);
    }
    
    void operator>>=(cdrStream&) const ;
    void operator<<=(cdrStream&) ;

    static _core_attr insertExceptionToAny    insertToAnyFn;
    static _core_attr insertExceptionToAnyNCP insertToAnyFnNCP;

    virtual ::CORBA::Exception* _NP_duplicate() const;

    static _core_attr const char* _PD_repoId;
    static _core_attr const char* _PD_typeId;

  private:
    virtual const char* _NP_typeId() const;
    virtual const char* _NP_repoId(int*) const;
    virtual void _NP_marshal(cdrStream&) const;
  };

#ifndef __Classes_mGestionClasses__
#define __Classes_mGestionClasses__
  class GestionClasses;
  class _objref_GestionClasses;
  class _impl_GestionClasses;
  
  typedef _objref_GestionClasses* GestionClasses_ptr;
  typedef GestionClasses_ptr GestionClassesRef;

  class GestionClasses_Helper {
  public:
    typedef GestionClasses_ptr _ptr_type;

    static _ptr_type _nil();
    static _CORBA_Boolean is_nil(_ptr_type);
    static void release(_ptr_type);
    static void duplicate(_ptr_type);
    static void marshalObjRef(_ptr_type, cdrStream&);
    static _ptr_type unmarshalObjRef(cdrStream&);
  };

  typedef _CORBA_ObjRef_Var<_objref_GestionClasses, GestionClasses_Helper> GestionClasses_var;
  typedef _CORBA_ObjRef_OUT_arg<_objref_GestionClasses,GestionClasses_Helper > GestionClasses_out;

#endif

  // interface GestionClasses
  class GestionClasses {
  public:
    // Declarations for this interface type.
    typedef GestionClasses_ptr _ptr_type;
    typedef GestionClasses_var _var_type;

    static _ptr_type _duplicate(_ptr_type);
    static _ptr_type _narrow(::CORBA::Object_ptr);
    static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
    
    static _ptr_type _nil();

    static inline void _marshalObjRef(_ptr_type, cdrStream&);

    static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
      omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static inline _ptr_type _fromObjRef(omniObjRef* o) {
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static _core_attr const char* _PD_repoId;

    // Other IDL defined within this scope.
    
  };

  class _objref_GestionClasses :
    public virtual ::CORBA::Object,
    public virtual omniObjRef
  {
  public:
    // IDL operations
    ListeNoms* listerClasses();
    ListeNoms* listerEtudiants(const char* nomClasse);

    // Constructors
    inline _objref_GestionClasses()  { _PR_setobj(0); }  // nil
    _objref_GestionClasses(omniIOR*, omniIdentity*);

  protected:
    virtual ~_objref_GestionClasses();

    
  private:
    virtual void* _ptrToObjRef(const char*);

    _objref_GestionClasses(const _objref_GestionClasses&);
    _objref_GestionClasses& operator = (const _objref_GestionClasses&);
    // not implemented

    friend class GestionClasses;
  };

  class _pof_GestionClasses : public _OMNI_NS(proxyObjectFactory) {
  public:
    inline _pof_GestionClasses() : _OMNI_NS(proxyObjectFactory)(GestionClasses::_PD_repoId) {}
    virtual ~_pof_GestionClasses();

    virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
    virtual _CORBA_Boolean is_a(const char*) const;
  };

  class _impl_GestionClasses :
    public virtual omniServant
  {
  public:
    virtual ~_impl_GestionClasses();

    virtual ListeNoms* listerClasses() = 0;
    virtual ListeNoms* listerEtudiants(const char* nomClasse) = 0;
    
  public:  // Really protected, workaround for xlC
    virtual _CORBA_Boolean _dispatch(omniCallHandle&);

  private:
    virtual void* _ptrToInterface(const char*);
    virtual const char* _mostDerivedRepoId();
    
  };


_CORBA_MODULE_END



_CORBA_MODULE POA_Classes
_CORBA_MODULE_BEG

  class GestionClasses :
    public virtual Classes::_impl_GestionClasses,
    public virtual ::PortableServer::ServantBase
  {
  public:
    virtual ~GestionClasses();

    inline ::Classes::GestionClasses_ptr _this() {
      return (::Classes::GestionClasses_ptr) _do_this(::Classes::GestionClasses::_PD_repoId);
    }
  };

_CORBA_MODULE_END



_CORBA_MODULE OBV_Classes
_CORBA_MODULE_BEG

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr



inline void
Classes::GestionClasses::_marshalObjRef(::Classes::GestionClasses_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}



#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_classes
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_classes
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_classes
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_classes
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_classes
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_classes
#endif

#endif  // __classes_hh__

